/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.matrimony.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.matrimony.model.SubCaste;
import com.matrimony.model.SubCasteModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the SubCaste service. Represents a row in the &quot;matrimony_subcaste&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.matrimony.model.SubCasteModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SubCasteImpl}.
 * </p>
 *
 * @author matrimony
 * @see SubCasteImpl
 * @see com.matrimony.model.SubCaste
 * @see com.matrimony.model.SubCasteModel
 * @generated
 */
public class SubCasteModelImpl extends BaseModelImpl<SubCaste>
	implements SubCasteModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sub caste model instance should use the {@link com.matrimony.model.SubCaste} interface instead.
	 */
	public static final String TABLE_NAME = "matrimony_subcaste";
	public static final Object[][] TABLE_COLUMNS = {
			{ "subCasteId", Types.BIGINT },
			{ "casteId", Types.BIGINT },
			{ "name", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table matrimony_subcaste (subCasteId LONG not null primary key,casteId LONG,name VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table matrimony_subcaste";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.matrimony.model.SubCaste"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.matrimony.model.SubCaste"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.matrimony.model.SubCaste"),
			true);
	public static long CASTEID_COLUMN_BITMASK = 1L;
	public static long NAME_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.matrimony.model.SubCaste"));

	public SubCasteModelImpl() {
	}

	public long getPrimaryKey() {
		return _subCasteId;
	}

	public void setPrimaryKey(long primaryKey) {
		setSubCasteId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_subCasteId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return SubCaste.class;
	}

	public String getModelClassName() {
		return SubCaste.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("subCasteId", getSubCasteId());
		attributes.put("casteId", getCasteId());
		attributes.put("name", getName());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long subCasteId = (Long)attributes.get("subCasteId");

		if (subCasteId != null) {
			setSubCasteId(subCasteId);
		}

		Long casteId = (Long)attributes.get("casteId");

		if (casteId != null) {
			setCasteId(casteId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}
	}

	public long getSubCasteId() {
		return _subCasteId;
	}

	public void setSubCasteId(long subCasteId) {
		_subCasteId = subCasteId;
	}

	public long getCasteId() {
		return _casteId;
	}

	public void setCasteId(long casteId) {
		_columnBitmask |= CASTEID_COLUMN_BITMASK;

		if (!_setOriginalCasteId) {
			_setOriginalCasteId = true;

			_originalCasteId = _casteId;
		}

		_casteId = casteId;
	}

	public long getOriginalCasteId() {
		return _originalCasteId;
	}

	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			SubCaste.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SubCaste toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (SubCaste)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		SubCasteImpl subCasteImpl = new SubCasteImpl();

		subCasteImpl.setSubCasteId(getSubCasteId());
		subCasteImpl.setCasteId(getCasteId());
		subCasteImpl.setName(getName());

		subCasteImpl.resetOriginalValues();

		return subCasteImpl;
	}

	public int compareTo(SubCaste subCaste) {
		long primaryKey = subCaste.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		SubCaste subCaste = null;

		try {
			subCaste = (SubCaste)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = subCaste.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		SubCasteModelImpl subCasteModelImpl = this;

		subCasteModelImpl._originalCasteId = subCasteModelImpl._casteId;

		subCasteModelImpl._setOriginalCasteId = false;

		subCasteModelImpl._originalName = subCasteModelImpl._name;

		subCasteModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<SubCaste> toCacheModel() {
		SubCasteCacheModel subCasteCacheModel = new SubCasteCacheModel();

		subCasteCacheModel.subCasteId = getSubCasteId();

		subCasteCacheModel.casteId = getCasteId();

		subCasteCacheModel.name = getName();

		String name = subCasteCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			subCasteCacheModel.name = null;
		}

		return subCasteCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{subCasteId=");
		sb.append(getSubCasteId());
		sb.append(", casteId=");
		sb.append(getCasteId());
		sb.append(", name=");
		sb.append(getName());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.matrimony.model.SubCaste");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>subCasteId</column-name><column-value><![CDATA[");
		sb.append(getSubCasteId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>casteId</column-name><column-value><![CDATA[");
		sb.append(getCasteId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = SubCaste.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			SubCaste.class
		};
	private long _subCasteId;
	private long _casteId;
	private long _originalCasteId;
	private boolean _setOriginalCasteId;
	private String _name;
	private String _originalName;
	private long _columnBitmask;
	private SubCaste _escapedModelProxy;
}