/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.matrimony.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the City service. Represents a row in the &quot;city&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.matrimony.model.impl.CityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.matrimony.model.impl.CityImpl}.
 * </p>
 *
 * @author matrimony
 * @see City
 * @see com.matrimony.model.impl.CityImpl
 * @see com.matrimony.model.impl.CityModelImpl
 * @generated
 */
public interface CityModel extends BaseModel<City> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a city model instance should use the {@link City} interface instead.
	 */

	/**
	 * Returns the primary key of this city.
	 *
	 * @return the primary key of this city
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this city.
	 *
	 * @param primaryKey the primary key of this city
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the city ID of this city.
	 *
	 * @return the city ID of this city
	 */
	public long getCityId();

	/**
	 * Sets the city ID of this city.
	 *
	 * @param cityId the city ID of this city
	 */
	public void setCityId(long cityId);

	/**
	 * Returns the region ID of this city.
	 *
	 * @return the region ID of this city
	 */
	public long getRegionId();

	/**
	 * Sets the region ID of this city.
	 *
	 * @param regionId the region ID of this city
	 */
	public void setRegionId(long regionId);

	/**
	 * Returns the city name of this city.
	 *
	 * @return the city name of this city
	 */
	@AutoEscape
	public String getCityName();

	/**
	 * Sets the city name of this city.
	 *
	 * @param cityName the city name of this city
	 */
	public void setCityName(String cityName);

	/**
	 * Returns the status of this city.
	 *
	 * @return the status of this city
	 */
	public boolean getStatus();

	/**
	 * Returns <code>true</code> if this city is status.
	 *
	 * @return <code>true</code> if this city is status; <code>false</code> otherwise
	 */
	public boolean isStatus();

	/**
	 * Sets whether this city is status.
	 *
	 * @param status the status of this city
	 */
	public void setStatus(boolean status);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(City city);

	public int hashCode();

	public CacheModel<City> toCacheModel();

	public City toEscapedModel();

	public String toString();

	public String toXmlString();
}