/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.matrimony.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import com.matrimony.service.persistence.ProfileKeyValuePK;

import java.io.Serializable;

/**
 * The base model interface for the ProfileKeyValue service. Represents a row in the &quot;matrimony_profile_key&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.matrimony.model.impl.ProfileKeyValueModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.matrimony.model.impl.ProfileKeyValueImpl}.
 * </p>
 *
 * @author matrimony
 * @see ProfileKeyValue
 * @see com.matrimony.model.impl.ProfileKeyValueImpl
 * @see com.matrimony.model.impl.ProfileKeyValueModelImpl
 * @generated
 */
public interface ProfileKeyValueModel extends BaseModel<ProfileKeyValue> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a profile key value model instance should use the {@link ProfileKeyValue} interface instead.
	 */

	/**
	 * Returns the primary key of this profile key value.
	 *
	 * @return the primary key of this profile key value
	 */
	public ProfileKeyValuePK getPrimaryKey();

	/**
	 * Sets the primary key of this profile key value.
	 *
	 * @param primaryKey the primary key of this profile key value
	 */
	public void setPrimaryKey(ProfileKeyValuePK primaryKey);

	/**
	 * Returns the profile ID of this profile key value.
	 *
	 * @return the profile ID of this profile key value
	 */
	public long getProfileId();

	/**
	 * Sets the profile ID of this profile key value.
	 *
	 * @param profileId the profile ID of this profile key value
	 */
	public void setProfileId(long profileId);

	/**
	 * Returns the key ID of this profile key value.
	 *
	 * @return the key ID of this profile key value
	 */
	public long getKeyId();

	/**
	 * Sets the key ID of this profile key value.
	 *
	 * @param keyId the key ID of this profile key value
	 */
	public void setKeyId(long keyId);

	/**
	 * Returns the value ID of this profile key value.
	 *
	 * @return the value ID of this profile key value
	 */
	public long getValueId();

	/**
	 * Sets the value ID of this profile key value.
	 *
	 * @param valueId the value ID of this profile key value
	 */
	public void setValueId(long valueId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ProfileKeyValue profileKeyValue);

	public int hashCode();

	public CacheModel<ProfileKeyValue> toCacheModel();

	public ProfileKeyValue toEscapedModel();

	public String toString();

	public String toXmlString();
}