/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.matrimony.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the SubCaste service. Represents a row in the &quot;matrimony_subcaste&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.matrimony.model.impl.SubCasteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.matrimony.model.impl.SubCasteImpl}.
 * </p>
 *
 * @author matrimony
 * @see SubCaste
 * @see com.matrimony.model.impl.SubCasteImpl
 * @see com.matrimony.model.impl.SubCasteModelImpl
 * @generated
 */
public interface SubCasteModel extends BaseModel<SubCaste> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sub caste model instance should use the {@link SubCaste} interface instead.
	 */

	/**
	 * Returns the primary key of this sub caste.
	 *
	 * @return the primary key of this sub caste
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sub caste.
	 *
	 * @param primaryKey the primary key of this sub caste
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sub caste ID of this sub caste.
	 *
	 * @return the sub caste ID of this sub caste
	 */
	public long getSubCasteId();

	/**
	 * Sets the sub caste ID of this sub caste.
	 *
	 * @param subCasteId the sub caste ID of this sub caste
	 */
	public void setSubCasteId(long subCasteId);

	/**
	 * Returns the caste ID of this sub caste.
	 *
	 * @return the caste ID of this sub caste
	 */
	public long getCasteId();

	/**
	 * Sets the caste ID of this sub caste.
	 *
	 * @param casteId the caste ID of this sub caste
	 */
	public void setCasteId(long casteId);

	/**
	 * Returns the name of this sub caste.
	 *
	 * @return the name of this sub caste
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this sub caste.
	 *
	 * @param name the name of this sub caste
	 */
	public void setName(String name);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(SubCaste subCaste);

	public int hashCode();

	public CacheModel<SubCaste> toCacheModel();

	public SubCaste toEscapedModel();

	public String toString();

	public String toXmlString();
}