/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.matrimony.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the KeyValue service. Represents a row in the &quot;matrimony_key_value&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.matrimony.model.impl.KeyValueModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.matrimony.model.impl.KeyValueImpl}.
 * </p>
 *
 * @author matrimony
 * @see KeyValue
 * @see com.matrimony.model.impl.KeyValueImpl
 * @see com.matrimony.model.impl.KeyValueModelImpl
 * @generated
 */
public interface KeyValueModel extends BaseModel<KeyValue> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a key value model instance should use the {@link KeyValue} interface instead.
	 */

	/**
	 * Returns the primary key of this key value.
	 *
	 * @return the primary key of this key value
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this key value.
	 *
	 * @param primaryKey the primary key of this key value
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the value ID of this key value.
	 *
	 * @return the value ID of this key value
	 */
	public long getValueId();

	/**
	 * Sets the value ID of this key value.
	 *
	 * @param valueId the value ID of this key value
	 */
	public void setValueId(long valueId);

	/**
	 * Returns the key ID of this key value.
	 *
	 * @return the key ID of this key value
	 */
	public long getKeyId();

	/**
	 * Sets the key ID of this key value.
	 *
	 * @param keyId the key ID of this key value
	 */
	public void setKeyId(long keyId);

	/**
	 * Returns the name of this key value.
	 *
	 * @return the name of this key value
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this key value.
	 *
	 * @param name the name of this key value
	 */
	public void setName(String name);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(KeyValue keyValue);

	public int hashCode();

	public CacheModel<KeyValue> toCacheModel();

	public KeyValue toEscapedModel();

	public String toString();

	public String toXmlString();
}