/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.matrimony.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Profile service. Represents a row in the &quot;matrimony_profile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.matrimony.model.impl.ProfileModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.matrimony.model.impl.ProfileImpl}.
 * </p>
 *
 * @author matrimony
 * @see Profile
 * @see com.matrimony.model.impl.ProfileImpl
 * @see com.matrimony.model.impl.ProfileModelImpl
 * @generated
 */
public interface ProfileModel extends BaseModel<Profile> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a profile model instance should use the {@link Profile} interface instead.
	 */

	/**
	 * Returns the primary key of this profile.
	 *
	 * @return the primary key of this profile
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this profile.
	 *
	 * @param primaryKey the primary key of this profile
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the profile ID of this profile.
	 *
	 * @return the profile ID of this profile
	 */
	public long getProfileId();

	/**
	 * Sets the profile ID of this profile.
	 *
	 * @param profileId the profile ID of this profile
	 */
	public void setProfileId(long profileId);

	/**
	 * Returns the profile code of this profile.
	 *
	 * @return the profile code of this profile
	 */
	@AutoEscape
	public String getProfileCode();

	/**
	 * Sets the profile code of this profile.
	 *
	 * @param profileCode the profile code of this profile
	 */
	public void setProfileCode(String profileCode);

	/**
	 * Returns the created for my of this profile.
	 *
	 * @return the created for my of this profile
	 */
	@AutoEscape
	public String getCreatedForMy();

	/**
	 * Sets the created for my of this profile.
	 *
	 * @param createdForMy the created for my of this profile
	 */
	public void setCreatedForMy(String createdForMy);

	/**
	 * Returns the name of this profile.
	 *
	 * @return the name of this profile
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this profile.
	 *
	 * @param name the name of this profile
	 */
	public void setName(String name);

	/**
	 * Returns the gender of this profile.
	 *
	 * @return the gender of this profile
	 */
	public boolean getGender();

	/**
	 * Returns <code>true</code> if this profile is gender.
	 *
	 * @return <code>true</code> if this profile is gender; <code>false</code> otherwise
	 */
	public boolean isGender();

	/**
	 * Sets whether this profile is gender.
	 *
	 * @param gender the gender of this profile
	 */
	public void setGender(boolean gender);

	/**
	 * Returns the birth date with time of this profile.
	 *
	 * @return the birth date with time of this profile
	 */
	public Date getBirthDateWithTime();

	/**
	 * Sets the birth date with time of this profile.
	 *
	 * @param birthDateWithTime the birth date with time of this profile
	 */
	public void setBirthDateWithTime(Date birthDateWithTime);

	/**
	 * Returns the rasi of this profile.
	 *
	 * @return the rasi of this profile
	 */
	@AutoEscape
	public String getRasi();

	/**
	 * Sets the rasi of this profile.
	 *
	 * @param rasi the rasi of this profile
	 */
	public void setRasi(String rasi);

	/**
	 * Returns the star of this profile.
	 *
	 * @return the star of this profile
	 */
	@AutoEscape
	public String getStar();

	/**
	 * Sets the star of this profile.
	 *
	 * @param star the star of this profile
	 */
	public void setStar(String star);

	/**
	 * Returns the dosam of this profile.
	 *
	 * @return the dosam of this profile
	 */
	@AutoEscape
	public String getDosam();

	/**
	 * Sets the dosam of this profile.
	 *
	 * @param dosam the dosam of this profile
	 */
	public void setDosam(String dosam);

	/**
	 * Returns the religion of this profile.
	 *
	 * @return the religion of this profile
	 */
	@AutoEscape
	public String getReligion();

	/**
	 * Sets the religion of this profile.
	 *
	 * @param religion the religion of this profile
	 */
	public void setReligion(String religion);

	/**
	 * Returns the caste of this profile.
	 *
	 * @return the caste of this profile
	 */
	@AutoEscape
	public String getCaste();

	/**
	 * Sets the caste of this profile.
	 *
	 * @param caste the caste of this profile
	 */
	public void setCaste(String caste);

	/**
	 * Returns the sub caste of this profile.
	 *
	 * @return the sub caste of this profile
	 */
	@AutoEscape
	public String getSubCaste();

	/**
	 * Sets the sub caste of this profile.
	 *
	 * @param subCaste the sub caste of this profile
	 */
	public void setSubCaste(String subCaste);

	/**
	 * Returns the height of this profile.
	 *
	 * @return the height of this profile
	 */
	@AutoEscape
	public String getHeight();

	/**
	 * Sets the height of this profile.
	 *
	 * @param height the height of this profile
	 */
	public void setHeight(String height);

	/**
	 * Returns the weight of this profile.
	 *
	 * @return the weight of this profile
	 */
	@AutoEscape
	public String getWeight();

	/**
	 * Sets the weight of this profile.
	 *
	 * @param weight the weight of this profile
	 */
	public void setWeight(String weight);

	/**
	 * Returns the complexion of this profile.
	 *
	 * @return the complexion of this profile
	 */
	@AutoEscape
	public String getComplexion();

	/**
	 * Sets the complexion of this profile.
	 *
	 * @param complexion the complexion of this profile
	 */
	public void setComplexion(String complexion);

	/**
	 * Returns the mother tongue of this profile.
	 *
	 * @return the mother tongue of this profile
	 */
	@AutoEscape
	public String getMotherTongue();

	/**
	 * Sets the mother tongue of this profile.
	 *
	 * @param motherTongue the mother tongue of this profile
	 */
	public void setMotherTongue(String motherTongue);

	/**
	 * Returns the language known of this profile.
	 *
	 * @return the language known of this profile
	 */
	@AutoEscape
	public String getLanguageKnown();

	/**
	 * Sets the language known of this profile.
	 *
	 * @param languageKnown the language known of this profile
	 */
	public void setLanguageKnown(String languageKnown);

	/**
	 * Returns the marital status of this profile.
	 *
	 * @return the marital status of this profile
	 */
	@AutoEscape
	public String getMaritalStatus();

	/**
	 * Sets the marital status of this profile.
	 *
	 * @param maritalStatus the marital status of this profile
	 */
	public void setMaritalStatus(String maritalStatus);

	/**
	 * Returns the children of this profile.
	 *
	 * @return the children of this profile
	 */
	public int getChildren();

	/**
	 * Sets the children of this profile.
	 *
	 * @param children the children of this profile
	 */
	public void setChildren(int children);

	/**
	 * Returns the country of this profile.
	 *
	 * @return the country of this profile
	 */
	@AutoEscape
	public String getCountry();

	/**
	 * Sets the country of this profile.
	 *
	 * @param country the country of this profile
	 */
	public void setCountry(String country);

	/**
	 * Returns the state of this profile.
	 *
	 * @return the state of this profile
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this profile.
	 *
	 * @param state the state of this profile
	 */
	public void setState(String state);

	/**
	 * Returns the city of this profile.
	 *
	 * @return the city of this profile
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this profile.
	 *
	 * @param city the city of this profile
	 */
	public void setCity(String city);

	/**
	 * Returns the address of this profile.
	 *
	 * @return the address of this profile
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this profile.
	 *
	 * @param address the address of this profile
	 */
	public void setAddress(String address);

	/**
	 * Returns the pin code of this profile.
	 *
	 * @return the pin code of this profile
	 */
	@AutoEscape
	public String getPinCode();

	/**
	 * Sets the pin code of this profile.
	 *
	 * @param pinCode the pin code of this profile
	 */
	public void setPinCode(String pinCode);

	/**
	 * Returns the phone of this profile.
	 *
	 * @return the phone of this profile
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this profile.
	 *
	 * @param phone the phone of this profile
	 */
	public void setPhone(String phone);

	/**
	 * Returns the mobile of this profile.
	 *
	 * @return the mobile of this profile
	 */
	@AutoEscape
	public String getMobile();

	/**
	 * Sets the mobile of this profile.
	 *
	 * @param mobile the mobile of this profile
	 */
	public void setMobile(String mobile);

	/**
	 * Returns the email address of this profile.
	 *
	 * @return the email address of this profile
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this profile.
	 *
	 * @param emailAddress the email address of this profile
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the education of this profile.
	 *
	 * @return the education of this profile
	 */
	@AutoEscape
	public String getEducation();

	/**
	 * Sets the education of this profile.
	 *
	 * @param education the education of this profile
	 */
	public void setEducation(String education);

	/**
	 * Returns the profession of this profile.
	 *
	 * @return the profession of this profile
	 */
	@AutoEscape
	public String getProfession();

	/**
	 * Sets the profession of this profile.
	 *
	 * @param profession the profession of this profile
	 */
	public void setProfession(String profession);

	/**
	 * Returns the currency of this profile.
	 *
	 * @return the currency of this profile
	 */
	@AutoEscape
	public String getCurrency();

	/**
	 * Sets the currency of this profile.
	 *
	 * @param currency the currency of this profile
	 */
	public void setCurrency(String currency);

	/**
	 * Returns the annual income of this profile.
	 *
	 * @return the annual income of this profile
	 */
	@AutoEscape
	public String getAnnualIncome();

	/**
	 * Sets the annual income of this profile.
	 *
	 * @param annualIncome the annual income of this profile
	 */
	public void setAnnualIncome(String annualIncome);

	/**
	 * Returns the hobbies of this profile.
	 *
	 * @return the hobbies of this profile
	 */
	@AutoEscape
	public String getHobbies();

	/**
	 * Sets the hobbies of this profile.
	 *
	 * @param hobbies the hobbies of this profile
	 */
	public void setHobbies(String hobbies);

	/**
	 * Returns the about me of this profile.
	 *
	 * @return the about me of this profile
	 */
	@AutoEscape
	public String getAboutMe();

	/**
	 * Sets the about me of this profile.
	 *
	 * @param aboutMe the about me of this profile
	 */
	public void setAboutMe(String aboutMe);

	/**
	 * Returns the family value of this profile.
	 *
	 * @return the family value of this profile
	 */
	@AutoEscape
	public String getFamilyValue();

	/**
	 * Sets the family value of this profile.
	 *
	 * @param familyValue the family value of this profile
	 */
	public void setFamilyValue(String familyValue);

	/**
	 * Returns the family type of this profile.
	 *
	 * @return the family type of this profile
	 */
	@AutoEscape
	public String getFamilyType();

	/**
	 * Sets the family type of this profile.
	 *
	 * @param familyType the family type of this profile
	 */
	public void setFamilyType(String familyType);

	/**
	 * Returns the family status of this profile.
	 *
	 * @return the family status of this profile
	 */
	@AutoEscape
	public String getFamilyStatus();

	/**
	 * Sets the family status of this profile.
	 *
	 * @param familyStatus the family status of this profile
	 */
	public void setFamilyStatus(String familyStatus);

	/**
	 * Returns the security code of this profile.
	 *
	 * @return the security code of this profile
	 */
	@AutoEscape
	public String getSecurityCode();

	/**
	 * Sets the security code of this profile.
	 *
	 * @param securityCode the security code of this profile
	 */
	public void setSecurityCode(String securityCode);

	/**
	 * Returns the photo security code of this profile.
	 *
	 * @return the photo security code of this profile
	 */
	@AutoEscape
	public String getPhotoSecurityCode();

	/**
	 * Sets the photo security code of this profile.
	 *
	 * @param photoSecurityCode the photo security code of this profile
	 */
	public void setPhotoSecurityCode(String photoSecurityCode);

	/**
	 * Returns the last logged in of this profile.
	 *
	 * @return the last logged in of this profile
	 */
	public Date getLastLoggedIn();

	/**
	 * Sets the last logged in of this profile.
	 *
	 * @param lastLoggedIn the last logged in of this profile
	 */
	public void setLastLoggedIn(Date lastLoggedIn);

	/**
	 * Returns the status of this profile.
	 *
	 * @return the status of this profile
	 */
	public int getStatus();

	/**
	 * Sets the status of this profile.
	 *
	 * @param status the status of this profile
	 */
	public void setStatus(int status);

	/**
	 * Returns the scheme of this profile.
	 *
	 * @return the scheme of this profile
	 */
	public int getScheme();

	/**
	 * Sets the scheme of this profile.
	 *
	 * @param scheme the scheme of this profile
	 */
	public void setScheme(int scheme);

	/**
	 * Returns the horoscope of this profile.
	 *
	 * @return the horoscope of this profile
	 */
	public boolean getHoroscope();

	/**
	 * Returns <code>true</code> if this profile is horoscope.
	 *
	 * @return <code>true</code> if this profile is horoscope; <code>false</code> otherwise
	 */
	public boolean isHoroscope();

	/**
	 * Sets whether this profile is horoscope.
	 *
	 * @param horoscope the horoscope of this profile
	 */
	public void setHoroscope(boolean horoscope);

	/**
	 * Returns the created by of this profile.
	 *
	 * @return the created by of this profile
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this profile.
	 *
	 * @param createdBy the created by of this profile
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified by of this profile.
	 *
	 * @return the modified by of this profile
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this profile.
	 *
	 * @param modifiedBy the modified by of this profile
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the created date of this profile.
	 *
	 * @return the created date of this profile
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this profile.
	 *
	 * @param createdDate the created date of this profile
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this profile.
	 *
	 * @return the modified date of this profile
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this profile.
	 *
	 * @param modifiedDate the modified date of this profile
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the company ID of this profile.
	 *
	 * @return the company ID of this profile
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this profile.
	 *
	 * @param companyId the company ID of this profile
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this profile.
	 *
	 * @return the group ID of this profile
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this profile.
	 *
	 * @param groupId the group ID of this profile
	 */
	public void setGroupId(long groupId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Profile profile);

	public int hashCode();

	public CacheModel<Profile> toCacheModel();

	public Profile toEscapedModel();

	public String toString();

	public String toXmlString();
}